MODULE := IF
DEPENDENCIES := Caches MIPS_Processor
PACKAGE := work
SRCS := src/*.vhd test/src/*.vhd
MODULE_TESTBENCHES := Fetch_tb

$(eval $(call DEFINE_MODULE,$(MODULE),$(PACKAGE),$(SRCS),$(MODULE_TESTBENCHES),$(DEPENDENCIES)))
