MODULE := MEM
DEPENDENCIES :=
PACKAGE := work
SRCS := src/*.vhd test/src/*.vhd
MODULE_TESTBENCHES :=
#Memory_access_tb

$(eval $(call DEFINE_MODULE,$(MODULE),$(PACKAGE),$(SRCS),$(MODULE_TESTBENCHES),$(DEPENDENCIES)))
