MODULE := Caches
DEPENDENCIES := rjarzmik
PACKAGE := work
SRCS := src/*.vhd test/src/*.vhd
MODULE_TESTBENCHES := acache_tb acache_torture_tb

$(eval $(call DEFINE_MODULE,$(MODULE),$(PACKAGE),$(SRCS),$(MODULE_TESTBENCHES),$(DEPENDENCIES)))
